include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.mocks.dart'

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
