import 'dart:math';
import 'package:meta/meta.dart';

class QuoteService {
  static QuoteService _instance = QuoteService._internal();
  factory QuoteService() => _instance;

  QuoteService._internal();

  @visibleForTesting
  static set instance(QuoteService value) => _instance = value;
  static final List<String> _quotes = [
    'Small steps every day lead to big results.',
    'Keep going, you are doing great!',
    'Consistency is the key to mastery.',
    'Progress, not perfection.',
    'Every expert was once a beginner.',
    'Your future self will thank you.',
    'Make today count.',
    'Dream big, start small, act now.',
    'The secret of getting ahead is getting started.',
    'Success is the sum of small efforts repeated.',
    "Believe you can and you're halfway there.",
    "Don't wait for opportunity. Create it.",
    'Your only limit is you.',
    'Great things never come from comfort zones.',
    'The harder you work, the luckier you get.',
    'Wake up with determination. Go to bed with satisfaction.',
    'Little by little, a little becomes a lot.',
    "Don't stop until you're proud.",
    'Push yourself because no one else will.',
    'Sometimes later becomes never. Do it now.',
    'The best time to start was yesterday. The next best time is now.',
    'Focus on being productive instead of busy.',
    'You are capable of amazing things.',
    'Start where you are. Use what you have. Do what you can.',
    "Success doesn't just find you. You have to go out and get it.",
    'The key to success is to focus on goals, not obstacles.',
    "Don't wish for it. Work for it.",
    'Stay focused and never give up.',
    'Be stronger than your excuses.',
    "Your limitation—it's only your imagination.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't let yesterday take up too much of today.",
    "You didn't come this far to only come this far.",
    'Do something today that your future self will thank you for.',
    "Be so good they can't ignore you.",
    "If it doesn't challenge you, it won't change you.",
    'Make your passion your paycheck.',
    "Don't be afraid to fail. Be afraid not to try.",
    'Every accomplishment starts with the decision to try.',
    'Strive for progress, not perfection.',
    'The difference between who you are and who you want to be is what you do.',
    "Don't count the days. Make the days count.",
    'Be a warrior, not a worrier.',
    'Small progress is still progress.',
    "The only bad workout is the one you didn't do.",
    'Your habits define your future.',
    "Excellence is not a destination; it's a continuous journey.",
    'A little progress each day adds up to big results.',
    'Good things come to those who hustle.',
    'One day or day one. You decide.',
    'Prove them wrong.',
    'The pain you feel today will be the strength you feel tomorrow.',
    "Excuses don't burn calories.",
    "Your body can stand almost anything. It's your mind you have to convince.",
    'Discipline is choosing between what you want now and what you want most.',
    'You are one workout away from a good mood.',
    'Motivation gets you started. Habit keeps you going.',
    "Take care of your body. It's the only place you have to live.",
    'The only way to do great work is to love what you do.',
    "Don't stop when you're tired. Stop when you're done.",
    'Work hard in silence. Let success make the noise.',
    "Losers quit when they're tired. Winners quit when they've won.",
    'Dream it. Believe it. Build it.',
    'Life begins at the end of your comfort zone.',
    'Champions keep playing until they get it right.',
    "Don't practice until you get it right. Practice until you can't get it wrong.",
    'Success is walking from failure to failure with no loss of enthusiasm.',
    'Act as if what you do makes a difference. It does.',
    'Nothing will work unless you do.',
    'Your goals are the road maps that guide you.',
    'Either you run the day or the day runs you.',
    'Doubt kills more dreams than failure ever will.',
    'Today is your opportunity to build the tomorrow you want.',
    'Everything you can imagine is real.',
    'Success is liking yourself, liking what you do, and liking how you do it.',
    'Do what you have to do until you can do what you want to do.',
    'Change the world by being yourself.',
    'The future depends on what you do today.',
    'Stay patient and trust your journey.',
    'What you get by achieving your goals is not as important as what you become.',
    'If you want to achieve greatness, stop asking for permission.',
    'Life is 10% what happens to you and 90% how you react to it.',
    'Quality is not an act, it is a habit.',
    "Don't limit your challenges. Challenge your limits.",
    'Be the energy you want to attract.',
    'Stop doubting yourself. Work hard and make it happen.',
    "If you're tired of starting over, stop giving up.",
    "Today's struggle is tomorrow's strength.",
    'Winners never quit. Quitters never win.',
    'Build your own dreams, or someone else will hire you to build theirs.',
    "You are what you do, not what you say you'll do.",
    'Set goals that make you want to jump out of bed in the morning.',
    'Your positive action combined with positive thinking results in success.',
    'The expert in anything was once a beginner.',
    "Don't wait. The time will never be just right.",
    'Be the change you wish to see in the world.',
    'Turn your obstacles into opportunities.',
    'The harder the battle, the sweeter the victory.',
    "Invest in yourself. You're worth it.",
    'Stay hungry. Stay foolish.',
    "Create the life you can't wait to wake up to.",
  ];

  String getRandomQuote() {
    return _quotes[Random().nextInt(_quotes.length)];
  }
}
