// Mocks generated by Mockito 5.4.6 from annotations
// in hobbyist/test/unit/services/sound_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hobbyist/models/hobby.dart' as _i4;
import 'package:hobbyist/services/analytics_service.dart' as _i5;
import 'package:hobbyist/services/hobby_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HobbyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHobbyService extends _i1.Mock implements _i2.HobbyService {
  @override
  _i3.Future<List<_i4.Hobby>> loadHobbies() =>
      (super.noSuchMethod(
            Invocation.method(#loadHobbies, []),
            returnValue: _i3.Future<List<_i4.Hobby>>.value(<_i4.Hobby>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Hobby>>.value(
              <_i4.Hobby>[],
            ),
          )
          as _i3.Future<List<_i4.Hobby>>);

  @override
  _i3.Future<void> addHobby(_i4.Hobby? hobby) =>
      (super.noSuchMethod(
            Invocation.method(#addHobby, [hobby]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateHobby(_i4.Hobby? hobby) =>
      (super.noSuchMethod(
            Invocation.method(#updateHobby, [hobby]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHobby(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHobby, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Hobby?> toggleCompletion(String? hobbyId, String? date) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCompletion, [hobbyId, date]),
            returnValue: _i3.Future<_i4.Hobby?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Hobby?>.value(),
          )
          as _i3.Future<_i4.Hobby?>);

  @override
  _i3.Future<String?> getSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [key]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setSetting(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSetting, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveHobbies(List<_i4.Hobby>? hobbies) =>
      (super.noSuchMethod(
            Invocation.method(#saveHobbies, [hobbies]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#resetDatabase, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i5.AnalyticsService {
  @override
  _i3.Future<void> logAppOpen() =>
      (super.noSuchMethod(
            Invocation.method(#logAppOpen, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logScreenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [screenName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOnboardingComplete() =>
      (super.noSuchMethod(
            Invocation.method(#logOnboardingComplete, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logLandingView() =>
      (super.noSuchMethod(
            Invocation.method(#logLandingView, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logHobbyCreated({
    required String? hobbyId,
    required String? repeatMode,
    int? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logHobbyCreated, [], {
              #hobbyId: hobbyId,
              #repeatMode: repeatMode,
              #color: color,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logHobbyUpdated({
    required String? hobbyId,
    String? repeatMode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logHobbyUpdated, [], {
              #hobbyId: hobbyId,
              #repeatMode: repeatMode,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logHobbyDeleted({
    required String? hobbyId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logHobbyDeleted, [], {
              #hobbyId: hobbyId,
              #reason: reason,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logCompletionToggled({
    required String? hobbyId,
    required bool? completed,
    int? currentStreak,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCompletionToggled, [], {
              #hobbyId: hobbyId,
              #completed: completed,
              #currentStreak: currentStreak,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logStreakAchieved({
    required String? hobbyId,
    required int? streakCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logStreakAchieved, [], {
              #hobbyId: hobbyId,
              #streakCount: streakCount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logCompletionSound() =>
      (super.noSuchMethod(
            Invocation.method(#logCompletionSound, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logAnalyticsViewed() =>
      (super.noSuchMethod(
            Invocation.method(#logAnalyticsViewed, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSettingChanged({
    required String? settingName,
    required String? settingValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSettingChanged, [], {
              #settingName: settingName,
              #settingValue: settingValue,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logQuoteDisplayed() =>
      (super.noSuchMethod(
            Invocation.method(#logQuoteDisplayed, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logDatabaseQueryTime({
    required String? queryType,
    required int? durationMs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logDatabaseQueryTime, [], {
              #queryType: queryType,
              #durationMs: durationMs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logDailyStats({
    required int? totalHobbies,
    required int? completedToday,
    required double? averageCompletionRate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logDailyStats, [], {
              #totalHobbies: totalHobbies,
              #completedToday: completedToday,
              #averageCompletionRate: averageCompletionRate,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSessionEnd({required int? durationSeconds}) =>
      (super.noSuchMethod(
            Invocation.method(#logSessionEnd, [], {
              #durationSeconds: durationSeconds,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFirstHobbyCreated() =>
      (super.noSuchMethod(
            Invocation.method(#logFirstHobbyCreated, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFirstCompletion() =>
      (super.noSuchMethod(
            Invocation.method(#logFirstCompletion, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
